// <auto-generated />
using System;
using HarryPotterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace universeexplorer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200105202206_AddedColumns")]
    partial class AddedColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HarryPotterApi.Models.SchoolHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("HouseName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SchoolHouses");
                });

            modelBuilder.Entity("HarryPotterApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("PlaysQuidditch")
                        .HasColumnType("boolean");

                    b.Property<int?>("SchoolHouseId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolHouseId");

                    b.HasIndex("StudentsId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HarryPotterApi.Models.Student", b =>
                {
                    b.HasOne("HarryPotterApi.Models.SchoolHouse", null)
                        .WithMany("Students")
                        .HasForeignKey("SchoolHouseId");

                    b.HasOne("HarryPotterApi.Models.Student", "Students")
                        .WithMany()
                        .HasForeignKey("StudentsId");
                });
#pragma warning restore 612, 618
        }
    }
}
